# Site settings
title: Review Note
email: asache3@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://asache3.github.io" # the base hostname & protocol for your site
twitter_username: asache3
github_username: asache3

# Build settings
markdown: kramdown
